# build_windows.ps1
# Build script for QuickTube on Windows 10/11
# Run this script in PowerShell as Administrator (or ensure you have write permissions in the folder)

# Force TLS 1.2 for safer downloads
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Write-Host "Building QuickTube for Windows..." -ForegroundColor Cyan

# --- CLEANUP ---
# Remove venv if broken
if (Test-Path "venv") {
    if (-not (Test-Path "venv\Scripts\pip.exe")) {
        Write-Host "Cleaning old/invalid venv..." -ForegroundColor Yellow
        Remove-Item "venv" -Recurse -Force
    }
}
if (-not (Test-Path "bin")) { New-Item -ItemType Directory -Force -Path "bin" | Out-Null }

# --- 1. SETUP PYTHON & DOWNLOAD SVTPLAY-DL VIA PIP ---
if (-not (Test-Path "venv")) {
    Write-Host "Creating virtual environment..." -ForegroundColor Yellow
    python -m venv venv
}

Write-Host "Installing dependencies and tools..." -ForegroundColor Yellow
# We install svtplay-dl via pip to get a correct .exe generated by pip in venv/Scripts
& .env\Scripts\pip.exe install pyinstaller svtplay-dl

# Copy the generated svtplay-dl.exe from venv to bin
if (Test-Path "venv\Scripts\svtplay-dl.exe") {
    Write-Host "Found svtplay-dl via pip, copying to bin/..." -ForegroundColor Green
    Copy-Item "venv\Scripts\svtplay-dl.exe" -Destination "bin\svtplay-dl.exe" -Force
} else {
    Write-Error "Could not find svtplay-dl.exe in venv/Scripts after installation."
    exit 1
}

# --- 2. DOWNLOAD YT-DLP ---
Write-Host "Downloading yt-dlp.exe..." -ForegroundColor Yellow
try {
    Invoke-WebRequest -Uri "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe" -OutFile "bin\yt-dlp.exe" -UserAgent "QuickTubeBuilder/1.0"
} catch {
    Write-Error "Could not download yt-dlp. Check internet connection."
    exit 1
}

# --- 3. DOWNLOAD GUM ---
$gumVersion = "0.14.5"
$gumUrl = "https://github.com/charmbracelet/gum/releases/download/v$gumVersion/gum_${gumVersion}_Windows_x86_64.zip"
$gumZip = "gum.zip"

if (-not (Test-Path "bin\gum.exe")) {
    Write-Host "Downloading gum..." -ForegroundColor Yellow
    try {
        Invoke-WebRequest -Uri $gumUrl -OutFile $gumZip -UserAgent "QuickTubeBuilder/1.0"
        Expand-Archive -Path $gumZip -DestinationPath "gum_temp" -Force
        
        $extractedGumPath = "gum_temp\gum_${gumVersion}_Windows_x86_64\gum.exe"
        if (Test-Path $extractedGumPath) {
            Move-Item -Path $extractedGumPath -Destination "bin\gum.exe" -Force
        } else {
            Write-Error "Could not find gum.exe in zip file."
            exit 1
        }
    } catch {
        Write-Error "Failed to download gum."
        exit 1
    } finally {
        if (Test-Path $gumZip) { Remove-Item $gumZip }
        if (Test-Path "gum_temp") { Remove-Item "gum_temp" -Recurse -Force }
    }
}

# --- 4. BUILD ---
Write-Host "Running PyInstaller..." -ForegroundColor Cyan
& .env\Scripts\pyinstaller.exe --onefile --clean --noconfirm `
    --add-binary "bin\gum.exe;bin" `
    --add-binary "bin\yt-dlp.exe;bin" `
    --add-binary "bin\svtplay-dl.exe;bin" `
    --name "quicktube" `
    quicktube.py

if (Test-Path "dist\quicktube.exe") {
    Write-Host ""
    Write-Host "✅ SUCCESS! File located here:" -ForegroundColor Green
    Write-Host "   $(Get-Location)\dist\quicktube.exe" -ForegroundColor White
} else {
    Write-Host "❌ Build failed." -ForegroundColor Red
}

Pause
